# Generated by Django 4.2.23 on 2025-06-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('etsy', 'Etsy'), ('woocommerce', 'WooCommerce'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], max_length=20)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_user_id', models.CharField(blank=True, max_length=100)),
                ('platform_username', models.CharField(blank=True, max_length=100)),
                ('shop_name', models.CharField(blank=True, max_length=100)),
                ('shop_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('expired', 'Token Expired')], default='active', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_product_id', models.CharField(blank=True, max_length=100)),
                ('platform_url', models.URLField(blank=True)),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('custom_description', models.TextField(blank=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_tags', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('draft', 'Draft'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='channels.connectedchannel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'channel')},
            },
        ),
    ]
